### The Symmetry Problem in Neural Networks

demonstrate this by initializing all weights and biases to zero and performing a forward pass.

In [1]:
import numpy as np

# --- 1. Define Network Parameters ---
n_input = 3   # Number of input features
n_hidden = 4  # Number of neurons in the hidden layer
n_output = 2  # Number of neurons in the output layer

# --- 2. Initialize Weights and Biases to Zero ---
# Hidden layer weights (input_features x hidden_units)
#W_h = np.zeros((n_input, n_hidden))
W_h = np.full((n_input, n_hidden),0.1)
# Hidden layer biases (1 x hidden_units)
b_h = np.full((1, n_hidden),0.1)


# Output layer weights (hidden_units x output_units)
W_o = np.full((n_hidden, n_output),0.1)

# Output layer biases (1 x output_units)
b_o = np.full((1, n_output),0.1)


print("--- Initialized Weights and Biases (all zeros) ---")
print("Hidden Layer Weights (W_h):\n", W_h)
print("Hidden Layer Biases (b_h):\n", b_h)
print("Output Layer Weights (W_o):\n", W_o)
print("Output Layer Biases (b_o):\n", b_o)

--- Initialized Weights and Biases (all zeros) ---
Hidden Layer Weights (W_h):
 [[0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1]]
Hidden Layer Biases (b_h):
 [[0.1 0.1 0.1 0.1]]
Output Layer Weights (W_o):
 [[0.1 0.1]
 [0.1 0.1]
 [0.1 0.1]
 [0.1 0.1]]
Output Layer Biases (b_o):
 [[0.1 0.1]]


In [2]:
import numpy as np

# --- 3. Input Data ---
X = np.array([[1.0, 0.5, -0.2]]) # A single input example

print("\n--- Input Data (X) ---")
print(X)

# --- 4. Forward Pass ---

# Hidden Layer Calculation
# Z_h = X @ W_h + b_h
Z_h = np.dot(X, W_h) + b_h

# Apply an activation function (e.g., ReLU for simplicity)
# ReLU(x) = max(0, x)
# In this case, since Z_h will be all zeros, A_h will also be all zeros.
A_h = np.maximum(0, Z_h)

print("\n--- Hidden Layer Activations (A_h) ---")
print("Notice all neurons in the hidden layer have the exact same activation:\n", A_h)

# Output Layer Calculation
# Z_o = A_h @ W_o + b_o
Z_o = np.dot(A_h, W_o) + b_o

# Apply output activation (e.g., linear for simplicity)
A_o = Z_o

print("\n--- Output Layer Activations (A_o) ---")
print("Notice all neurons in the output layer have the exact same activation:\n", A_o)

print("\n--- Conclusion ---")
print("As observed, when all weights and biases are initialized to zero, every neuron in the hidden layer computes the exact same value (in this case, zero). Consequently, every neuron in the output layer also computes the same value. This demonstrates the symmetry problem: without diverse initializations, neurons cannot learn distinct features.")


--- Input Data (X) ---
[[ 1.   0.5 -0.2]]

--- Hidden Layer Activations (A_h) ---
Notice all neurons in the hidden layer have the exact same activation:
 [[0.23 0.23 0.23 0.23]]

--- Output Layer Activations (A_o) ---
Notice all neurons in the output layer have the exact same activation:
 [[0.192 0.192]]

--- Conclusion ---
As observed, when all weights and biases are initialized to zero, every neuron in the hidden layer computes the exact same value (in this case, zero). Consequently, every neuron in the output layer also computes the same value. This demonstrates the symmetry problem: without diverse initializations, neurons cannot learn distinct features.
